#!/bin/sh
while $(true) ; do
    code=0
	awesome --no-argb $@ >> $HOME/.cache/awesome_stdout  2>> $HOME/.cache/awesome_stderr || code=$?
    if [[ ${code} -eq 2 ]] ; then
        awesome $@ >> $HOME/.cache/awesome_stdout  2>> $HOME/.cache/awesome_stderr
    elif [[ ${code} -ne 0 ]] ; then
        (sleep 2 ; openbox) ||
            xterm
        sleep 2
    fi
done
