#!/bin/sh
CACHEDIR=$HOME/.cache
if test ! -d ${CACHEDIR} ; then
    mkdir -p ${CACHEDIR}
fi
while $(true) ; do
    awesome $@ >> ${CACHEDIR}/awesome_stdout  2>> ${CACHEDIR}/awesome_stderr ||
        (sleep 1 ; openbox) ||
            xterm
    sleep 1
done
